// Generated by https://quicktype.io

package io.quicktype;

import java.util.Map;

public class TopLevel {
    public Double doubleValue;
    public Long integerValue;
    public Boolean boolValue;
    public String stringValue;
    public Object[] anythingArrayValue;
    public Map<String, Object> anythingMapValue;
}

