# Generated by https://quicktype.io

from typing import List


class Item:
    title: str
    link: str
    thumbnail: str
    sizeheight: int
    sizewidth: int

    def __init__(self, title: str, link: str, thumbnail: str, sizeheight: int, sizewidth: int) -> None:
        self.title = title
        self.link = link
        self.thumbnail = thumbnail
        self.sizeheight = sizeheight
        self.sizewidth = sizewidth


class TopLevel:
    last_build_date: str
    total: int
    start: int
    display: int
    items: List[Item]

    def __init__(self, last_build_date: str, total: int, start: int, display: int, items: List[Item]) -> None:
        self.last_build_date = last_build_date
        self.total = total
        self.start = start
        self.display = display
        self.items = items
